name: Aggiorna Annunci

on:
  schedule:
    - cron: "*/10 * * * *"  # Ogni 10 minuti
  workflow_dispatch:       # Permette avvio manuale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clona repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Esegui script
        run: python update.py

      - name: Commit file aggiornato
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add annunci.json
          git commit -m "Aggiornamento automatico annunci" || echo "Nessuna modifica"
          git push
